theme: jekyll-theme-minimal
pages:
- ["index.md", "Homepage"]
- ["compile.md", "_compile"]
- ["cythonhook.md", "_cythonhook"]
- ["database.md", "_database"]
- ["compilepytyhonjit.md", "compilepythonjit"]
