theme: jekyll-theme-minimal
pages:
- ["index.md", "Homepage"]
- ["compile.md", "compile"]
- ["cythonhook.md", "cythonhook"]
- ["database.md", "database"]
- ["compilepytyhonjit.md", "compilepythonjit"]
